name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-346627c1a2d60744722afb4cd639f-prodbucket-wubyh80dd4f9
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
